# # Opacity
# active-opacity = 1.0;
# inactive-opacity = 1.0;
#
# # Do not dim the status bar or floating popups
# focus-exclude = [
#     "class_g = 'i3bar'",
#     "class_g = 'Polybar'",
#     "window_type = 'dock'",
#     "window_type = 'desktop'"
# ];
#
# # Fixed dimming (0.0 to 1.0)
# inactive-dim = 0.0;
#
# backend = "glx";
# corner-radius = 10;
# detect-client-opacity = true;
# detect-rounded-corners = true;
#
# rounded-corners-exclude = [
#   "class_g = 'i3bar'",
#   "class_g = 'Polybar'",
#   "window_type = 'dock'",
#   "window_type = 'desktop'"
# ];
#
shadow = true;
shadow-radius = 1;
shadow-opacity = .3;
shadow-offset-x = 5;
shadow-offset-y = 5;

shadow-exclude = [
  "class_g = 'i3bar'",
  "class_g = 'Polybar'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
